/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegulatorRouteImport } from './routes/regulator'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegulatorShipmentIdRouteImport } from './routes/regulator.$shipmentId'
import { Route as ApiPublicControlRouteImport } from './routes/api/public/control'
import { Route as ApiPublicStreamShipmentIdRouteImport } from './routes/api/public/stream.$shipmentId'
import { Route as ApiPublicReadingsShipmentIdRouteImport } from './routes/api/public/readings.$shipmentId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorRoute = RegulatorRouteImport.update({
  id: '/regulator',
  path: '/regulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulatorShipmentIdRoute = RegulatorShipmentIdRouteImport.update({
  id: '/$shipmentId',
  path: '/$shipmentId',
  getParentRoute: () => RegulatorRoute,
} as any)
const ApiPublicControlRoute = ApiPublicControlRouteImport.update({
  id: '/api/public/control',
  path: '/api/public/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamShipmentIdRoute =
  ApiPublicStreamShipmentIdRouteImport.update({
    id: '/api/public/stream/$shipmentId',
    path: '/api/public/stream/$shipmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReadingsShipmentIdRoute =
  ApiPublicReadingsShipmentIdRouteImport.update({
    id: '/api/public/readings/$shipmentId',
    path: '/api/public/readings/$shipmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/driver': typeof DriverRoute
  '/manager': typeof ManagerRoute
  '/regulator': typeof RegulatorRouteWithChildren
  '/reports': typeof ReportsRoute
  '/regulator/$shipmentId': typeof RegulatorShipmentIdRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/readings/$shipmentId': typeof ApiPublicReadingsShipmentIdRoute
  '/api/public/stream/$shipmentId': typeof ApiPublicStreamShipmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/driver': typeof DriverRoute
  '/manager': typeof ManagerRoute
  '/regulator': typeof RegulatorRouteWithChildren
  '/reports': typeof ReportsRoute
  '/regulator/$shipmentId': typeof RegulatorShipmentIdRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/readings/$shipmentId': typeof ApiPublicReadingsShipmentIdRoute
  '/api/public/stream/$shipmentId': typeof ApiPublicStreamShipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/driver': typeof DriverRoute
  '/manager': typeof ManagerRoute
  '/regulator': typeof RegulatorRouteWithChildren
  '/reports': typeof ReportsRoute
  '/regulator/$shipmentId': typeof RegulatorShipmentIdRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/readings/$shipmentId': typeof ApiPublicReadingsShipmentIdRoute
  '/api/public/stream/$shipmentId': typeof ApiPublicStreamShipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/driver'
    | '/manager'
    | '/regulator'
    | '/reports'
    | '/regulator/$shipmentId'
    | '/api/public/control'
    | '/api/public/readings/$shipmentId'
    | '/api/public/stream/$shipmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/driver'
    | '/manager'
    | '/regulator'
    | '/reports'
    | '/regulator/$shipmentId'
    | '/api/public/control'
    | '/api/public/readings/$shipmentId'
    | '/api/public/stream/$shipmentId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/driver'
    | '/manager'
    | '/regulator'
    | '/reports'
    | '/regulator/$shipmentId'
    | '/api/public/control'
    | '/api/public/readings/$shipmentId'
    | '/api/public/stream/$shipmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DriverRoute: typeof DriverRoute
  ManagerRoute: typeof ManagerRoute
  RegulatorRoute: typeof RegulatorRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ApiPublicControlRoute: typeof ApiPublicControlRoute
  ApiPublicReadingsShipmentIdRoute: typeof ApiPublicReadingsShipmentIdRoute
  ApiPublicStreamShipmentIdRoute: typeof ApiPublicStreamShipmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator': {
      id: '/regulator'
      path: '/regulator'
      fullPath: '/regulator'
      preLoaderRoute: typeof RegulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulator/$shipmentId': {
      id: '/regulator/$shipmentId'
      path: '/$shipmentId'
      fullPath: '/regulator/$shipmentId'
      preLoaderRoute: typeof RegulatorShipmentIdRouteImport
      parentRoute: typeof RegulatorRoute
    }
    '/api/public/control': {
      id: '/api/public/control'
      path: '/api/public/control'
      fullPath: '/api/public/control'
      preLoaderRoute: typeof ApiPublicControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/$shipmentId': {
      id: '/api/public/stream/$shipmentId'
      path: '/api/public/stream/$shipmentId'
      fullPath: '/api/public/stream/$shipmentId'
      preLoaderRoute: typeof ApiPublicStreamShipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/readings/$shipmentId': {
      id: '/api/public/readings/$shipmentId'
      path: '/api/public/readings/$shipmentId'
      fullPath: '/api/public/readings/$shipmentId'
      preLoaderRoute: typeof ApiPublicReadingsShipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegulatorRouteChildren {
  RegulatorShipmentIdRoute: typeof RegulatorShipmentIdRoute
}

const RegulatorRouteChildren: RegulatorRouteChildren = {
  RegulatorShipmentIdRoute: RegulatorShipmentIdRoute,
}

const RegulatorRouteWithChildren = RegulatorRoute._addFileChildren(
  RegulatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DriverRoute: DriverRoute,
  ManagerRoute: ManagerRoute,
  RegulatorRoute: RegulatorRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ApiPublicControlRoute: ApiPublicControlRoute,
  ApiPublicReadingsShipmentIdRoute: ApiPublicReadingsShipmentIdRoute,
  ApiPublicStreamShipmentIdRoute: ApiPublicStreamShipmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
